"""base

Revision ID: 0e21ceb6d915
Revises: dd9e4a1efe62
Create Date: 2024-02-09 15:19:17.283688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e21ceb6d915'
down_revision = 'dd9e4a1efe62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
