"""base

Revision ID: 192ed82afcde
Revises: 600c858e5931
Create Date: 2024-02-10 00:15:13.193065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '192ed82afcde'
down_revision = '600c858e5931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
