"""base

Revision ID: 35353f75b17d
Revises: 0e21ceb6d915
Create Date: 2024-02-10 00:00:58.415508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35353f75b17d'
down_revision = '0e21ceb6d915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
