"""base

Revision ID: 3fb4c25b2c34
Revises: 35353f75b17d
Create Date: 2024-02-10 00:04:42.616668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb4c25b2c34'
down_revision = '35353f75b17d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
