"""base

Revision ID: 600c858e5931
Revises: 8d27e4a21893
Create Date: 2024-02-10 00:13:14.444769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600c858e5931'
down_revision = '8d27e4a21893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
