"""base

Revision ID: 8d27e4a21893
Revises: 3fb4c25b2c34
Create Date: 2024-02-10 00:05:43.346005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d27e4a21893'
down_revision = '3fb4c25b2c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
