"""base

Revision ID: a46420baa364
Revises: b3551c1a8048
Create Date: 2024-02-10 00:18:50.933622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46420baa364'
down_revision = 'b3551c1a8048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
