"""base

Revision ID: 9d71e275baac
Revises: a93105fabf08
Create Date: 2024-02-16 18:10:15.966432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d71e275baac'
down_revision = 'a93105fabf08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
