"""newchat

Revision ID: 9e023ffb9270
Revises: bc96cdd1a0fd
Create Date: 2024-02-21 08:09:34.074353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e023ffb9270'
down_revision = 'bc96cdd1a0fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
