"""datetime

Revision ID: a93105fabf08
Revises: c0b85977eed2
Create Date: 2024-02-16 18:01:27.440443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a93105fabf08'
down_revision = 'c0b85977eed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
