"""activation_code

Revision ID: c0b85977eed2
Revises: f5b550923b86
Create Date: 2024-02-16 16:51:42.855168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b85977eed2'
down_revision = 'f5b550923b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_activation_code_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_activation_code_key', 'users', ['activation_code'])
    # ### end Alembic commands ###
