"""user

Revision ID: f5b550923b86
Revises: fa8fa217a6db
Create Date: 2024-02-16 16:36:44.813875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b550923b86'
down_revision = 'fa8fa217a6db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
